### ISSUE TITLE
Unable to generate module configuration

### ISSUE THREAD

**Issue by aellert** [puppetlabs/puppetlabs-kubernetes#237]
Hi,

According to the documentation, the first thing to do is to generate the module configuration (actually version 3.1.0), so I used this command line

```
$ docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:3.1.0
Unable to find image 'puppet/kubetool:3.1.0' locally
docker: Error response from daemon: manifest for puppet/kubetool:3.1.0 not found.
See 'docker run --help'.
```
Then I went to [Docker hub](https://hub.docker.com/r/puppet/kubetool) and saw that the latest version available is 3.0.1

```
$ docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:3.0.1
Unable to find image 'puppet/kubetool:3.0.1' locally
3.0.1: Pulling from puppet/kubetool
ab7e51e37a18: Pull complete 
442b117d3b3d: Pull complete 
7f1f0257edc6: Pull complete 
65d6b2a929c4: Pull complete 
ca30673f8d08: Pull complete 
a2b9a2e642d5: Pull complete 
a8eb8d54ab04: Pull complete 
b0dae2a0db53: Pull complete 
Digest: sha256:e7e386247d6fe14a26e4e16fac2d25122c720af50076cf59d1260b334fc296d5
Status: Downloaded newer image for puppet/kubetool:3.0.1
/etc/k8s/kube_tool/other_params.rb:9:in `create': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
	from /etc/k8s/kube_tool.rb:63:in `build_hiera'
	from /etc/k8s/kube_tool.rb:77:in `<main>'
```
Can you please help ?
Thank you for you help.

Alexandre

**Comment by aellert** [comment]
Works with puppet/kubetool:3.0.1.
And I realize my env file was empty...
